cmmiMongo/config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :steps
  resources :roles
  resources :projects
  resources :processareas
  resources :practices
  resources :levels
  resources :goals
  resources :goals
  devise_for :users

 root :to => 'welcome#index'

end

cmmiMongo/app/models/processarea.rb
class Processarea < ActiveRecord::Base
	belongs_to :level

	has_many :goals
end

cmmiMongo/app/controllers/processareas_controller.rb
class ProcessareasController < ApplicationController
  before_action :set_processarea, only: [:show, :edit, :update, :destroy]

  # GET /processareas
  # GET /processareas.json
  def index
    @processareas = Processarea.all
  end

  # GET /processareas/1
  # GET /processareas/1.json
  def show
  end

  # GET /processareas/new
  def new
    @processarea = Processarea.new
  end

  # GET /processareas/1/edit
  def edit
  end

  # POST /processareas
  # POST /processareas.json
  def create
    @processarea = Processarea.new(processarea_params)

    respond_to do |format|
      if @processarea.save
        format.html { redirect_to @processarea, notice: 'Processarea was successfully created.' }
        format.json { render :show, status: :created, location: @processarea }
      else
        format.html { render :new }
        format.json { render json: @processarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /processareas/1
  # PATCH/PUT /processareas/1.json
  def update
    respond_to do |format|
      if @processarea.update(processarea_params)
        format.html { redirect_to @processarea, notice: 'Processarea was successfully updated.' }
        format.json { render :show, status: :ok, location: @processarea }
      else
        format.html { render :edit }
        format.json { render json: @processarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /processareas/1
  # DELETE /processareas/1.json
  def destroy
    @processarea.destroy
    respond_to do |format|
      format.html { redirect_to processareas_url, notice: 'Processarea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_processarea
      @processarea = Processarea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def processarea_params
      params.require(:processarea).permit(:n_level, :t_name, :t_description)
    end
end

cmmiMongo/app/helpers/processareas_helper.rb
module ProcessareasHelper
end

cmmiMongo/app/views/processareas/_form.html.erb
<%= form_for(@processarea) do |f| %>
  <% if @processarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@processarea.errors.count, "error") %> prohibited this processarea from being saved:</h2>

      <ul>
      <% @processarea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :n_level %><br>
    <%= f.number_field :n_level %>
  </div>
  <div class="field">
    <%= f.label :t_name %><br>
    <%= f.text_field :t_name %>
  </div>
  <div class="field">
    <%= f.label :t_description %><br>
    <%= f.text_field :t_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cmmiMongo/app/views/processareas/edit.html.erb
<h1>Editing Processarea</h1>

<%= render 'form' %>

<%= link_to 'Show', @processarea %> |
<%= link_to 'Back', processareas_path %>

cmmiMongo/app/views/processareas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Processareas</h1>

<table>
  <thead>
    <tr>
      <th>N level</th>
      <th>T name</th>
      <th>T description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @processareas.each do |processarea| %>
      <tr>
        <td><%= processarea.n_level %></td>
        <td><%= processarea.t_name %></td>
        <td><%= processarea.t_description %></td>
        <td><%= link_to 'Show', processarea %></td>
        <td><%= link_to 'Edit', edit_processarea_path(processarea) %></td>
        <td><%= link_to 'Destroy', processarea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Processarea', new_processarea_path %>

cmmiMongo/app/views/processareas/new.html.erb
<h1>New Processarea</h1>

<%= render 'form' %>

<%= link_to 'Back', processareas_path %>

cmmiMongo/app/views/processareas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>N level:</strong>
  <%= @processarea.n_level %>
</p>

<p>
  <strong>T name:</strong>
  <%= @processarea.t_name %>
</p>

<p>
  <strong>T description:</strong>
  <%= @processarea.t_description %>
</p>

<%= link_to 'Edit', edit_processarea_path(@processarea) %> |
<%= link_to 'Back', processareas_path %>