cmmiMongo/config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :steps
  resources :roles
  resources :projects
  resources :processareas
  resources :practices
  resources :levels
  resources :goals
  resources :goals
  devise_for :users

 root :to => 'welcome#index'

end

cmmiMongo/app/models/practice.rb
class Practice < ActiveRecord::Base
	belongs_to :goal
	validates :t_name, presence: true
	has_many :steps
end

cmmiMongo/app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: [:show, :edit, :update, :destroy]

  # GET /practices
  # GET /practices.json
  def index
    @practices = Practice.all
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit
  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)

    respond_to do |format|
      if @practice.save
        format.html { redirect_to @practice, notice: 'Practice was successfully created.' }
        format.json { render :show, status: :created, location: @practice }
      else
        format.html { render :new }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url, notice: 'Practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      params.require(:practice).permit(:t_name, :t_description, :n_goal)
    end
end

cmmiMongo/app/helpers/practices_helper.rb
module PracticesHelper
end

cmmiMongo/app/views/practices/_form.html.erb
<%= form_for(@practice) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br>Nombre</br>
    <%= f.text_field :t_name %>
  </div>
  <div class="field">
    <br>Descripcion</br>
    <%= f.text_field :t_description %>
  </div>
  <div class="field">
    Meta</br>
    <%= f.number_field :n_goal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cmmiMongo/app/views/practices/edit.html.erb
<h1>Editing Practice</h1>

<%= render 'form' %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

cmmiMongo/app/views/practices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listas de practicas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Meta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
      <tr>
        <td><%= practice.t_name %></td>
        <td><%= practice.t_description %></td>
        <td><%= practice.n_goal %></td>
        <td><%= link_to 'Ver', practice %></td>
        <td><%= link_to 'Editar', edit_practice_path(practice) %></td>
        <td><%= link_to 'Eliminar', practice, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva practica', new_practice_path %>

cmmiMongo/app/views/practices/new.html.erb
<h1>Nueva practica</h1>

<%= render 'form' %>

<%= link_to 'Regresar', practices_path %>

cmmiMongo/app/views/practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @practice.t_name %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @practice.t_description %>
</p>

<p>
  <strong>Meta:</strong>
  <%= @practice.n_goal %>
</p>

<%= link_to 'Editar', edit_practice_path(@practice) %> |
<%= link_to 'Regresar', practices_path %>