cmmiMongo/config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :steps
  resources :roles
  resources :projects
  resources :processareas
  resources :practices
  resources :levels
  resources :goals
  resources :goals
  devise_for :users

 root :to => 'welcome#index'

end

cmmiMongo/app/models/company.rb
class Company < ActiveRecord::Base
	validates :t_name, presence: true
end

cmmiMongo/app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :processarea
	validates :t_name, presence: true
	has_many :practices
end

cmmiMongo/app/models/level.rb
class Level < ActiveRecord::Base
	validates :t_name, presence: true
	has_many :processareas
end

cmmiMongo/app/models/practice.rb
class Practice < ActiveRecord::Base
	belongs_to :goal
	validates :t_name, presence: true
	has_many :steps
end

cmmiMongo/app/models/processarea.rb
class Processarea < ActiveRecord::Base
	belongs_to :level

	has_many :goals
end

cmmiMongo/app/models/project.rb
class Project < ActiveRecord::Base
	validates :t_name, presence: true
end

cmmiMongo/app/models/role.rb
class Role < ActiveRecord::Base

	has_many :users
end

cmmiMongo/app/models/step.rb
class Step < ActiveRecord::Base
	belongs_to :user, :practice
	validates :t_description, presence: true
end

cmmiMongo/app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :steps
end

cmmiMongo/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:n_processArea, :t_name, :t_description, :t_type)
    end
end

cmmiMongo/app/helpers/application_helper.rb
module ApplicationHelper
end

cmmiMongo/app/helpers/companies_helper.rb
module CompaniesHelper
end

cmmiMongo/app/helpers/goals_helper.rb
module GoalsHelper
end

cmmiMongo/app/helpers/levels_helper.rb
module LevelsHelper
end

cmmiMongo/app/helpers/practices_helper.rb
module PracticesHelper
end

cmmiMongo/app/helpers/processareas_helper.rb
module ProcessareasHelper
end

cmmiMongo/app/helpers/projects_helper.rb
module ProjectsHelper
end

cmmiMongo/app/helpers/roles_helper.rb
module RolesHelper
end

cmmiMongo/app/helpers/steps_helper.rb
module StepsHelper
end

cmmiMongo/app/helpers/welcome_helper.rb
module WelcomeHelper
end

cmmiMongo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmmiMongo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,300,900' rel='stylesheet' type='text/css'>
</head>
<body>

<HEADER>
	<nav class="be-red white large-padding">
		<ul class="no-list row center-xs middle-xs">
			<li class="col-md">
				<h1 class="no-margin" id="logo">CMMI-Dev</h1>
			</li> 
			<li class="col-md">
				<%= link_to "Inicio  ", root_path %>
			</li>
			<li class="col-md">
				<%= link_to "Compañia  ", companies_path %>
			</li>
			<li class="col-md">
				<%= link_to "Proyecto  ", projects_path %>
			</li>
			<li class="col-md">
				<%= link_to "Practica  ", practices_path %>
			</li>
			<li class="col-md">
				<%= link_to "Tarea  ", steps_path %>
			</li>
			<li class="col-md">
				<div id="user_nav">
				  <% if user_signed_in? %>
				    Sesión como: <%= current_user.email %>.				     
				     Sino?
				    <%= link_to "Cerrar Sesión", destroy_user_session_path %>
				  <% else %>
				    <%= link_to "Crear Sesión", new_user_registration_path %> o
				    <%= link_to "iniciar Sesión", new_user_session_path %>
				  <% end %>
				</div>
			</li>
		</ul>
	</nav>
</HEADER>

<%= yield %>
	<footer>
		<div class="row center-xs">
		  <div class="col-xs-8 col-md-6">
		    <div class="box text-left"><p id="notice"><%= notice %></p>
		    	<p>Rafael Malagon 20081020053. Diego Ortiz 20081020068. Edwin Paez 20081020072.</p>
		    </div>    
		  </div>
		</div>
	</footer>
</body>
</html>